name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Get tags
        run: git fetch --tags origin
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'

      - name: Decode Keystore File
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$KEYSTORE" | base64 --decode > android/app/key.jks

      - name: Create key.properties
        run: |
          echo "storeFile=key.jks" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "releasePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "releaseAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk

      - uses: actions/upload-artifact@v3
        with:
          name: simple-calorie-counter
          path: build/app/outputs/apk/release/app-release.apk
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
            tag_name: release-${{ github.run_number }}
            release_name: Release release-${{ github.run_number }}
            draft: false
            prerelease: false
  
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./build/app/outputs/apk/release/app-release.apk
            asset_name: app-release.apk
            asset_content_type: application/vnd.android.package-archive